### ISSUE TITLE
Getting value of a specific property

### ISSUE THREAD

**Issue by belett** [Nudin/LexData#10]
Caveat: I'm a newbie so maybe it already exist.

How do I get the value of a specific property? `L.claims.values()` gives me all the values but I only want one (P5187 in my specific case).

**Comment by Nudin** [comment]
Should be as simple as:
`L.claims["P5185"]
`
Or did I misunderstood?

**Comment by Nudin** [comment]
Please reopen or ping me on Wikidata if you still have (this) issues.
